export const STATUS_SUCCESS = 200
export const STATUS_CREATED = 201
export const STATUS_BAD_REQUEST = 400
export const STATUS_FORBIDDEN = 400
export const STATUS_UNAUTHORIZED = 401
export const STATUS_NOTFOUND = 404
export const STATUS_UNPROCESSABLE_ENTITY = 422
export const STATUS_ERROR = 500
