
export type HttpNames = 'success'
|'created'
|'accepted'
|'badRequest'
|'unauthorized'
|'invalidSession'
|'forbidden'
|'notFound'
|'userNotFound'
|'integrationError'
|'teaPot'
|'unprocessableEntity'
|'internalError'
|'notImplemented'
