export enum FILE_EXTENSIONS {
  'video/mp4' = 'mp4',
  'audio/ogg; codecs=opus' = 'ogg',
  'audio/mpeg' = 'mp3',
  'image/gif' = 'gif',
  'image/jpeg' = 'jpg',
  'image/svg+xml' = 'svg',
  'image/tiff' = 'tiff',
  'image/png' = 'png',
  'image/bmp' = 'bmp',
  'text/html' = 'html',
  'text/csv' = 'csv',
  'text/css' = 'css',
  'text/plain' = 'txt',
  'text/xml' = 'xml',
  'text/tab-separated-values' = 'tsv',
  'application/pdf' = 'pdf',
  'application/xml' = 'xml',
  'application/zip' = 'zip',
  'application/x-compressed-zip' = 'zip',
  'application/vnd.ms-excel' = 'xls',
  'application/x-bzip2' = 'bz2',
  'application/msword' = 'doc',
  'application/x-gzip' = 'gz',
  'application/java-archive' = 'jar',
  'application/x-javascript' = 'js',
  'application/vnd.ms-powerpoint' = 'ppt',
  'application/x-tar' = 'tar.gz'
}
